### ISSUE TITLE
[Bug]: Dosn't play videos launched from Droid Dashcam

### ISSUE THREAD

**Issue by vertigo220** [nova-video-player/aos-AVP#1080]
### Problem description

All other video players I tried will play videos recorded and launched by Droid Dashcam (DroidCoolApps), but Nova does not, though it will play the videos if opened via Nova directly or a file manager app. So something about how Droid Dashcam directs it to play the video is problematic with Nova. It just loads a black/blank screen with no controls.

### Steps to reproduce the issue

1) Make a recording with Droid Dashcam
2) Navigate to the recording in Droid Dashcam and play it and select Nova

### Expected behavior

The video should play, as it does in every other player

### Your phone/tablet/androidTV model

S

### Operating system version

Android 13

### Application version and app store

6.2.54, Droid-ify

**Comment by courville** [comment]
Should be fixed by commit in https://github.com/nova-video-player/aos-AVP/issues/1095

**Comment by vertigo220** [comment]
@courville Has this commit made it to release yet? I just updated to the newest version and still having the problem. Playing the video results in a blank screen, going into the file info it shows the error "Did not manage to access the file."

**Comment by courville** [comment]
I am able to open the video with

**Comment by courville** [comment]
Yes it is in the release. I tried with droid dashcam and indeed I cannot open the video (it pops up nova but with black screen).
However I can open it through a file browser without any issue.
This is strange.

**Comment by vertigo220** [comment]
The dev of that app is very responsive, so if you need info from them I'm sure they'd be helpful in figuring it out.
