### ISSUE TITLE
Opensubtitles subtitles

### ISSUE THREAD

**Issue by kingslay** [nova-video-player/aos-AVP#1228]
### Problem description

I cannot log in with an opensubtitles.org account, but I can log in with an opensubtitles.com account. However, I cannot search for subtitles with an opensubtitles.com account. The text says that subtitles cannot be found on opensubtitles.org. So I think the app needs to clarify whether it should use an opensubtitles.com or opensubtitles.org account.

### Steps to reproduce the issue

Can't find online subtitles for any movie

### Your phone/tablet/androidTV model

Vidda

### Operating system version

Android 12

**Comment by okey2k** [comment]
same here.

**Comment by courville** [comment]
I just fixed the translations on crowdin that had still a reference to opensubtitles.org.
For clarification, as stated in the FAQ, opensubtitles.com credential need to be used now since opensubtitle.org API service has been deprecated for applications.
Could you try latest nova version to check if the issue you describe is still valid https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.86 ? This version is being reviewed for publication on Google Play.
If this does not work, please provide the exact filename of the video on which you search for subtitles for me to reproduce.
Note that it would help if you provide nova version number on which you have the issue and on which store and device you are having the issue.

**Comment by kingslay** [comment]
I downloaded the latest installation package org.courville.nova-2599607-6.2.86-20240622.2032-arm64-v8a-release from github. I still have this problem
The name of the movie is
Dune.Part.Two.2024.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX.mkv

**Comment by courville** [comment]
I have checked with latest nova version and this very specific filename and I was able to download french subs.
Could you please check that you have selected a language to download subs and let me know which locale you are using (language) and which language you request to download subs?

**Comment by kingslay** [comment]
Subtitles and app language are both cn(Chinese)

**Comment by courville** [comment]
User in https://github.com/nova-video-player/aos-AVP/issues/1137#issuecomment-2156361151 has reported that:

> For Chinese users, don't be confused in the subtitles setting, you should chose Chinese(Sim) or Chinese(Trad) in the second half of the language list instead of Chinese at the Top, which will give you nothing for most subtitles.

It might be the solution.
If this is the case I might have to do manual mapping to correct the default behavior.
Please report and more importantly, tell me which I should select by default for Chinese users (sorry for my lack of knowledge).

**Comment by kingslay** [comment]
Your solution is OK. Thank you. Thank you. You can use Chinese(Sim) （simplified Chinese ）first.

**Comment by okey2k** [comment]
Update on using org.courville.nova-2599607-6.2.86-20240622.2032-armeabi-v7a-release.apk
1. After provide my own opensubtitles.com credential, download subtitle quota still limited to 20/day, screenshot as follows:
![IMG_20240625_093654](https://github.com/nova-video-player/aos-AVP/assets/32120698/a5744ac2-8af5-4574-b4f0-4a64a76683bd)

2. Avatar2 cannot find Chinese(Sim) or Chinese(Trad) subtitles, which is impossible, file name as below:
Avatar.The.Way.of.Water.2022.2160p.WEB-DL.DDP5.1.Atmos.HEVC-CMRG.mkv
![IMG_20240625_093609](https://github.com/nova-video-player/aos-AVP/assets/32120698/418f223a-80b9-40a7-b958-622460812a6c)
 
3. The text on the prompt is still showing connecting to www.opensubtitles.org which is confusing on the latest version.
![IMG_20240625_093607](https://github.com/nova-video-player/aos-AVP/assets/32120698/8aa66373-db51-4993-b183-50c01ae4bec0)
![IMG_20240625_093428](https://github.com/nova-video-player/aos-AVP/assets/32120698/2d649143-2617-4576-b6b9-33685193a622)


Other than above, all good for me.

Thanks for the great job!

**Comment by courville** [comment]
> 1. After provide my own opensubtitles.com credential, download subtitle quota still limited to 20/day, screenshot as follows:

Unless you have a VIP account that you pay for, without credentials you are limited to 5/day and logged in you get 20/day.
Please let me know if VIP status on nova is not processed correctly (I do not have a VIP account).

> 2. Avatar2 cannot find Chinese(Sim) or Chinese(Trad) subtitles, which is impossible, file name as below:
>    Avatar.The.Way.of.Water.2022.2160p.WEB-DL.DDP5.1.Atmos.HEVC-CMRG.mkv

I will check.

> 3. The text on the prompt is still showing connecting to [www.opensubtitles.org](http://www.opensubtitles.org) which is confusing on the latest version.

Release with opensubtitles.com instead of opensubtitles.org has not published yet.

**Comment by courville** [comment]
@okey2k, Avatar subs not found will be fixed in next release.

**Comment by courville** [comment]
> Your solution is OK. Thank you. Thank you. You can use Chinese(Sim) （simplified Chinese ）first.

opensubtitles knows only zh-tw (traditional Chinese) and zh-cn (simplified Chinese).
I thus have forced any other locale starting with zh (e.g. zh-mo) to fallback to zh-cn.
It can be overriden by a correct choice in the subs favorite language download nova setting.

@okey2k I hope this will fix bad default behavior and address your earlier comments.

**Comment by courville** [comment]
https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.87 is out for testing

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-AVP/issues/1129

My final takeways.

* basic Chinese howto for lost occidental nova coder
  * zh-cn Chinese (Mainland China): Mandarin (mostly in Simplified charset)
  * zh-tw Chinese (Taiwan): Min (mostly in Traditional charset)
  * zh-hk Chinese (Hong Kong): Cantonese
  * Character set = Simplified or Traditional
* opensubtitles
  * zh-ca = Chinese (Cantonese) -> zh-hk Chinese (Hong Kong),
  * zh-cn = Chinese (simplified) -> zh-cn Chinese (Mainland China),
  * zh-tw = Chinese (traditional) -> zh-tw Chinese (Taiwan)
  * ze = Chinese bilingual -> Chinese Cantonese + English

**Comment by courville** [comment]
I will add zh-ca that is missing and rename all Chinese entries.
