### ISSUE TITLE
[Bug]: Custom nfo files not being read when rescraping

### ISSUE THREAD

**Issue by RaizinStack** [nova-video-player/aos-AVP#1341]
### Problem description

Nova does not seem to read the nfo files at all when rescraping the library. I've also tried turning off my internet to force it to scrape from the public folder but it just gets stuck. 

### Steps to reproduce the issue

1. Open Nova for the first time and let it scan everything then auto-export nfo.
2. Delete the exported nfo files created by Nova itself.
3. Put custom nfo files in public application folder 
`/sdcard/Android/data/org.courville.nova/files/nfoPoster` (mine has it as `GalaxyA12` instead of `sdcard`
4. Click `remove info` from the episode.
5. Click the `rescrape all without description`

### Expected behavior

nfo files should automatically be read from the public folder but rescraping just reads it from tmdb instead.

### Your phone/tablet/androidTV model

Galaxy A12

### Operating system version

Android 12

### Application version and app store

v6.3.13-20241211.2228 from IzzyOnDroid

### Additional system information

Some things to note, I'm on an android device with an SD card inserted. All my shows are on the SD card, and I'm placing the nfo files in internal storage. I've also tried manually creating the `/files/nfoPoster` to place the nfo files in before opening Nova for the first time and it still won't read it.

**Comment by YANYUTIN** [comment]
I encountered a similar issue and would like to suggest the option to prioritize reading local NFO files. Some files have already been scraped, and re-scraping them online might cause errors.

**Comment by courville** [comment]
Seems that the feature has been broken since the changes made to comply with API30 (MANAGE_EXTERNAL_STORAGE not granted by Google to nova). With the changes that I just pushed it should help.

**Comment by darki15** [comment]
@courville No, it didn't help. I updated to 6.3.16, but Nova still does not read the nfo files placed in files/nfoPoster

**Comment by RaizinStack** [comment]
Update 6.3.16 did fix the issue for me, albeit a manual one. All I did was click `remove info`, move my nfo to the 'nfoPoster' folder, and after click 'get info'. It opened a search window that showed me the correct details using my custom nfo.

**Comment by darki15** [comment]
Strange, that doesn't work for me. "Get info" doesn't show me my nfo file.

**Comment by CossieLover1369** [comment]
I have the exact same issue which has only happened in the last month or so. 
 I create .nfo files using tinymediamanager on PC for my files which are stored on an external ssd which is plugged into a Sony x94j TV running upto date Android 12. Nova version is 6.4.3-20250521.1917.
 Nova always recognised my .nfo files and my movies and series just showed up without issue (sometimes automatically and sometimes after a rescan of the storage). Recently it won't read .nfo files at all and newly added files just appeared in the non scraped folder but files already present were fine and the info appeared as usual. I then tried resetting the app to see if that would fix Nova not reading the newer .nfo files but now it won't read any of them and I just have all my movies and series jumbled up in the non scraped folder. 
 The reason I don't scrape and use local .nfo instead is because scraping gets a lot wrong and won't even find some. Did something change with Nova in this past month or 2 to cause this? Pulling my hair out with it as I've tried everything.
