### ISSUE TITLE
Get info for unscrapped videos (Nova 6.4.5)

### ISSUE THREAD

**Issue by darki15** [nova-video-player/aos-AVP#1508]
Hi,

I noticed that if I manually search for video info for unscrapped videos, the search function only looks for movies. I can't search for series; Nova or the integrated TMDB search function doesn't find a single one, only movies. But again: This only applies to unscrapped videos.

**Comment by darki15** [comment]
@courville Are you aware of this bug? It's still there.

**Comment by courville** [comment]
Should be fixed in next release.

**Comment by darki15** [comment]
@courville Can't see a big difference in your new release 6.4.20.

Still not possible to scrap some movies/series. Examples:
https://www.themoviedb.org/tv/4709-man-vs-wild
https://www.themoviedb.org/tv/113707-hindenburg
https://www.themoviedb.org/tv/235886-zwei-weihnachtsmanner

It would help if Nova would search for both movies AND series when do a manual search.

**Comment by courville** [comment]
Damn. Can you please provide me with exact filename you have and language of scrape? This way I will be able to reproduce your use case.

**Comment by darki15** [comment]
@courville In the past, I experimented with different filenames to see if a change would help. Then, I gave up. Currently, the files are named as follows:

1. Abenteuer.Survival.720p.S01E01.mkv
2. Hindenburg Teil 1 (2011).mkv
3. Zwei.Weihnachtsmaenner.Teil1.2008.mkv

I use German language.

**Comment by courville** [comment]
OK I tried, and got a match with manual search on:
* Hindenburg Teil 1 (2011).mkv -> with Hindenburg s01e01 (tiel 1 is not matched for mini series)
* Abenteuer.Survival.720p.S01E01.mkv -> Abenteuer.Survival s01e01 (720p should always be after the s01e01)

**Comment by darki15** [comment]
Ah nice, tried and worked for me aswell. Thanks!
