### ISSUE TITLE
Cannot display file info or play video from search results

### ISSUE THREAD

**Issue by drm-nz** [nova-video-player/aos-AVP#439]
Hi There,

I use Nova Player on Android. My files are stored on a NAS that I'm accessing via SMB. When I list my files, everything looks fine. When I click on a video, I can see the file info and can play without any problems. But when I search for a file and I click on the video name in the search results, I get a "Did not manage to access the file".

So, in other words this works:
* Open Nova Player
* Hamburger meny on the top left > Movies
* Select a video 
* Click "Play from the beginning"

And this doesn't:
* Open Nova Player
* Click on the magnifier/search con
* Type in a name from the list that you know it exists
* Pick the item from the autocomplete search results
* Notice that there's no info loaded
* When you click on "Play from beginning", you get a toast message saying "Cannot play video"

Device: Xiaomi Mi Mix 2S
Android: Android 10 QKQ1.190828.002, MIUI 12.0.3 (QDGMIXM)

Same for movies as well as TV Shows. Can someone please have a look?

Cheers,
Laz

**Comment by courville** [comment]
Indeed this is a bug: thx for the report.

**Comment by drm-nz** [comment]
Hey Guys,

Any chance we can get this fixed sometime soon-ish? This is a major functionality on the main screen that has been broken for a very long time. 

Cheers, 
Laz

**Comment by courville** [comment]
This is fixed in the upcoming V6 release. Pushed on Amazon. Can be sideloaded with github release.

**Comment by drm-nz** [comment]
Thank you, very much appreciated.

Cheers,
Laz

**Comment by drm-nz** [comment]
Hi There,

I've just received the v6.0.65 update on f-droid and this functionality is still broken. Can you please confirm the version number that this fix is in?

Cheers,
Laz

**Comment by drm-nz** [comment]
Still an issue in yesterday's release v6.0.67

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-AVP/issues/655

**Comment by courville** [comment]
Indeed it was only working for local storage and not remote shares.

**Comment by drm-nz** [comment]
Received v6.0.71 today. I can confirm that this is working now. Thanks!

**Comment by logicapi** [comment]
I get this same issue but only when accessing via UPnP  Windows Media Server library (network). Still is annoying, though. Not sure what is causing this. I tried tweaking permissions on the Windows side, playing with my A95L'S capabilities, nothing worked.
