### ISSUE TITLE
[Bug]: No DTS-HD.MA audio issue with ffmpeg 5.0.1 (v6.0.61)

### ISSUE THREAD

**Issue by okan35** [nova-video-player/aos-AVP#621]
### Problem description

No audio from video

### Steps to reproduce the issue

Play the show and there will be no audio.

### Expected behavior

There should be audio

### Your phone/tablet/androidTV model

Xiaomi mi tv box s

### Operating system version

Android 9

### Application version and app store

v6.0.61

### Additional system information

There was audio on version v6.0.58 but not on v6.0.6 you can find more info about codec etc in text file
[Rome.2005.S01E03.An.Owl.in.a.Thornbush.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv.txt](https://github.com/nova-video-player/aos-AVP/files/8502206/Rome.2005.S01E03.An.Owl.in.a.Thornbush.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-NOGRP.mkv.txt)
1

**Comment by ffwell** [comment]
the same bug，no Dialogue sound。

**Comment by courville** [comment]
@okan35 and @ffwell based on your comment I infer this is a regression compared to previous versions. I have pushed a new 6.0.62 version on github reverting the ffmpeg upstep to be sure. Please check if it solves your issue.

**Comment by okan35** [comment]
For me this fixes the issue, thanks for the swift response.

**Comment by ffwell** [comment]
Unfortunately, my problem remains. Moreover, the video image quality is seriously stuck. I tried to install this software on the Android simulator of the computer, and found that there is a sound option on the Android simulator to the effect that multi-channel sounds can be mixed together for output (of course, this will sacrifice multi-channel), but install this software on Android TV. Without this option, the dialogue sound may not come out, but some background sounds occur. The above is only my personal situation. Thank you.

**Comment by courville** [comment]
@ffwell can you please confirm that you are NOT using passthrough option on Android TV? If you are not using it it will resort to software decoding and this should fix the problem (and still perhaps do multichannel depending on your configuration).
Could you please let me know the configuration you are using (tv brand, version, if you are using a soundbar/AV receiver etc.)? Also providing a link to the video file in question could help too.

**Comment by ffwell** [comment]
![1](https://user-images.githubusercontent.com/29617777/163797715-e0a99ebf-7d5f-4b8a-b8ee-45c25599357c.jpg)
![2](https://user-images.githubusercontent.com/29617777/163797726-360a695e-d0c7-4b36-ac1c-c82fc350aeea.jpg)

https://user-images.githubusercontent.com/29617777/163797733-4f2564be-562e-4ce7-b78e-71f18032493f.mp4

you see the video,no dialogue sound， but some background sounds

**Comment by courville** [comment]
@ffwell ok thanks: I get that you are not using any passthrough mode and you are loosing the voice channel (front ones) because of some reasons.
Can you please disclose the android device you are using? I could add an option to force stereo downmixing that would solve your particular (weird) case.

**Comment by ffwell** [comment]
ok，thx，the android device is HONOR X1(HUAWEI HarmonyOS 2)，Can you make changes on ffmpeg 5.0.1 (v6.0.61)? I really like the quality of the new version. It feels better.thx a lot

**Comment by courville** [comment]
@ffwell please try this build ONLY for you https://drive.google.com/file/d/147d3Xtni49O8LUSa0GgTALZltG85jmK3/view?usp=sharing (it is 6.0.62). If it works I will rework the logic so that it is android TV friendly.
And for the record, I think HarmonyOS is broken.

**Comment by ffwell** [comment]
Already tried,it works。the sound is ok，Thank you for your work.

**Comment by courville** [comment]
@ffwell thanks for the confirmation.
Note that in next release in your case you will have to enable new option to force downmixing in nova settings.

**Comment by ffwell** [comment]
@courville copy that, looking forward to, thank you.
