### ISSUE TITLE
Nova not available on Amazon Appstore for Fire TV

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#88]
Despite this answer to amazon support still no clue about why Fire TV is not listed in Nova compatibility

> I do have in the AndroidManifest.xml of the application:
>     <uses-feature
>         android:name="android.hardware.touchscreen"
>         android:required="false" />
> This can be verified on the submitted apk you do a aapt dump badging
> 2068517.apk | grep touch
>   uses-feature-not-required: name='android.hardware.touchscreen'
> 
> Please note that the same apk is on GooglePlay store and is accepted as for
> phone/tablet and AndroidTV.
> Could you let me know what prevents the same behavior on Amazon Appstore?

**Comment by courville** [comment]
Tested on a fireTV via adb install and the tv banner is not displayed (ugly icon): this consists perhaps in a lead.

**Comment by courville** [comment]
Latest apk made it possible to enable firetv devices. Should be fixed through tomorrow's deployment. Will reopen if not a reality.

**Comment by courville** [comment]
apk update enables to select fire tv devices.
However currently stuck on approval process: i) first attempt amazon requires credentials for testing (not required in reality), ii) second attempt submission denied because of non compliance without any details... Process is tedious and without actionable feedback provided.

**Comment by scruffynerf** [comment]
Still not on FireTV listings, despite being in Amazon Appstore (and in my library).  Sideloaded the GitHub version just fine, using Downloader app (which is easily found in appstore and super useful) and
Using 351271 aka
https://go.aftvnews.com/351271
(Which points to recent universal version url at GitHub)

**Comment by courville** [comment]
@scruffynerf indeed it failed last review due to sponsor link. I will remove it and resubmit. Thx for the heads up.
